apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-app
    name: nginx
  name: nginx-service
spec:
  selector:
    app: nginx-app
    name: nginx
  type: NodePort
  ports:
  - name: nginx-port
    port: 80
    protocol: TCP
    targetPort: nginx-port

